apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: wxsmart
      defaultBucket: soldering
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN:-wxsmart-dev-token}
    isDefault: true
    editable: true
